### ISSUE TITLE
[Bug]: Color schemes have excessively huge size (120+k), many attributes aren't needed

### ISSUE THREAD

**Issue by rvishnyakov** [mallowigi/material-theme-issues#116]
### Describe the bug

Users of IntelliJ are complaining that their "colors" config directory contains a lot of huge color schemes. It creates synchronization problems due to a limited remote storage size. A lot of attributes could be removed just by using proper inheritance ("inherit value from" flag checked), for example, keywords, classes, comments etc. The original idea was to use as much as possible from "Language Defaults" section and define only some attributes for specific languages where either the inheritance from language defaults is missing or an attribute must have its own definition to look nicer. Note that using inherited values instead of directly defined ones makes also easier to customize a color scheme since there will be only one place to change it for multiple languages: "Language Defaults".
It is also recommended to remove color scheme/console fonts by unchecking the flag "Use color scheme (console) font instead of default". Color scheme fonts will be dropped at some point because they are not portable between different OSes and screen resolutions.

### To Reproduce

Just choose any Material theme in Matherial Theme UI->Setttings->Select Theme

### Expected behavior

Smaller color scheme size.

### Material Theme Version

v7.2.1

### IDE

IntelliJ IDEA

**Comment by mallowigi** [comment]
Hi Rustam,

The reason why I bothered manually overriding the color scheme properties for each color is because many, many times, after an IDE update or for some random reason, the Darcula colors were leaking onto the color scheme.

For example, let's say I didn't define a color for TypeScript's classes. So by default it would inherit from either JavaScript class, Java Class or Language Defaults. All is good. 
Then one day after an update I would notice that the class color suddenly became a blue that isn't in the color schemes color, all of this because suddenly Darcula decided that this color should be manually set to Blue, and therefore all color schemes inheriting from Darcula would get this Blue color instead of the Language Defaults.

Then I tried replacing "parent-scheme" to something other than Darcula/Default, and the result was suboptimal. A lot of colors were missing which was even worse than Darcula leaking. After some research the reason why that many plugin vendors expect to have Darcula/Default as the parent scheme, so this was a no-no.

At this point there's not much I can do. Maybe there is a way to dynamically "build a color scheme", e.g. make an user check a list of wanted languages in order to build an optimal color scheme. For example if someone doesn't need C, Objective C, Groovy, Elixir, etc... But this would be a bit hard to do and to be honest not something I'd want to invest time on it. I'd be grateful if this was something provided by the SDK as this would prove useful to all theme vendors, which would probably have the same issues having to support many languages.

Letting this open for discussion, but I'm afraid I'm not going to fix it.
