### ISSUE TITLE
[Bug]: Line height cuts off text

### ISSUE THREAD

**Issue by quantumwebco** [mallowigi/material-theme-issues#265]
### Describe the bug

<img width="202" alt="image" src="https://user-images.githubusercontent.com/12368817/199969031-7f0faf72-dc12-41f0-abbb-0fd5adefc503.png">

### To Reproduce

Do a git merge, view conflicts. But also happens in other lists

### Expected behavior

No text cut off, line should be high enough to show all text

### Material Theme Version

Latest

### IDE

PHPStorm

**Comment by mallowigi** [comment]
This is a known issue. It's because the IDE doesn't expect you to change the line height of the tree items. If it works fine for most trees (project view, structure...) there are some trees that have the line height conflicting with the parent and render like you showed (basically trees that are inside tables).

Either dismiss it, reduce the line height or disable the plugin.
