### ISSUE TITLE
[Bug]: IDE tree indentation preferences inoperable when this theme is active

### ISSUE THREAD

**Issue by SatoshiGuacamole** [mallowigi/material-theme-issues#355]
### Describe the bug

My IntelliJ IDE provides me two options to change tree indentation in the project panel:
1. Settings > Appearance & Behavior > UI Options > Show smaller indents in trees
2. Registry > ide.ui.tree.indent

### Actual behavior

The amount of tree indentation in the project panel does not change when a user changes the setting (or registry value) of his/her IDE.

### To Reproduce

1. Set configuration for tree indentation using either of the mentioned settings.
2. Install this theme from the marketplace
3. Activate this theme

### Expected behavior

Tree indentation should be changed when a user changes the setting (or registry value) of his/her IDE.

### Material Theme Version

8.6.4

### IDE

PHPStorm

### System Info

```shell
PhpStorm 2023.1.2
macOS 13.2.1
Non-Bundled Plugins:
    com.chrisrm.idea.MaterialThemeUI (8.6.4)
```

### Logs/Screenshots

```shell
<application>
  <component name="MaterialThemeConfig">
    <option name="compactSidebar" value="true" />
    <option name="isCustomTreeIndentEnabled" value="true" />
    <option name="isTabsShadow" value="false" />
    <option name="isWizardShown" value="true" />
    <option name="pristineConfig" value="false" />
    <option name="indicatorStyle" value="None" />
    <option name="customSidebarHeight" value="20" />
    <option name="rightTreeIndent" value="4" />
    <option name="accentColor" value="2979ff" />
    <option name="selectedTheme" value="ONE_DARK" />
    <option name="userId" value="-5bd60a96:179d5f239d9:-8000" />
    <option name="version" value="8.6.4" />
  </component>
</application>

*material_theme.xml*

```xml
<application>
  <component name="MaterialCustomThemeConfig">
    <option name="excludedColor" value="2e3c43ff" />
    <option name="accentColor" value="009688ff" />
    <option name="notificationsColor" value="323232ff" />
    <option name="treeSelectionColor" value="546e7aff" />
    <option name="highlightColor" value="425b67ff" />
    <option name="secondBorderColor" value="2a373eff" />
    <option name="tableSelectedColor" value="314549ff" />
    <option name="contrastColor" value="1e272cff" />
    <option name="disabledColor" value="415967ff" />
    <option name="secondaryBackgroundColor" value="32424aff" />
    <option name="buttonColor" value="2e3c43ff" />
    <option name="selectionForegroundColor" value="ffffffff" />
    <option name="selectionBackgroundColor" value="546e7aff" />
    <option name="textColor" value="607d8bff" />
    <option name="foregroundColor" value="b0bec5ff" />
    <option name="backgroundColor" value="263238ff" />
  </component>
</application>
```
*material_custom_theme.xml*
```

**Comment by SatoshiGuacamole** [comment]
This may be a violation of section 13 of the [JetBrains Plugin Marketplace Developer Agreement](https://plugins.jetbrains.com/legal/developer-agreement) where it states:

```
You will not take any action that interferes with, damages, or accesses or uses in any unauthorized manner, the hardware, software, networks, technologies, or other properties or services of JetBrains or of any end user or other third party.
```

"You will not take any action that interferes with, damages, [...] software, [...] technologies, [...] of JetBrains or of any end user or other third party."

**Comment by mallowigi** [comment]
This is because we distribute our own indentation settings via the Project Tree Settings: https://material-theme.com/docs/configuration/project-view-settings/#custom-tree-indent

It's incompatible with the options provided by the native app, because we need to determine whether to use the one defined in the settings or the one from the registry.

But you might be right, it could be controlled via an "enabled" setting that when off, uses the one defined in the registry.

By the way, I'm not a big fan of the passive aggressive tone. This setting doesn't "damage software", it simply ignores a default setting by providing it's own. There are better ways to express yourself.

**Comment by SatoshiGuacamole** [comment]
Thank you for helping me understand that this is a technical issue and not a deliberate attempt at disabling functionality provided by Jetbrains.

The setting you showed me is unfortunately greyed out. That means it's inactive to start with so you may be able to use this instead of an enabled checkbox, saving on some development time I imagine.

In any case, I had no intention of overcoming passive aggressive. You may not have known about the builtin settings but I was under the impression this was broken deliberately, not due to technical constraints like you explained. Appologies for mentioning the developer agreement.

You make a wonderful theme, thanks.

**Comment by mallowigi** [comment]
I finally got the time to tackle this. Now it will take the indentation using the following flow:
- If the "Left Indent" and/or "Right indent" checkbox is checked, it will take the value from there
- Otherwise, it will check if the "use smaller indents in trees" is checked, in the case, the right indent only will become 0 (the original behavior)
- Otherwise, it will check if the registry value is not -1, in which case it will use the value defined there
- Else, it will use the default value provided by the plugin (left:10, right: 7)
