### ISSUE TITLE
[Bug]: List items in conflicts window have invalid height / improper alignment

### ISSUE THREAD

**Issue by jkazimierczak** [mallowigi/material-theme-issues#469]
### Describe the bug

In the resolve conflict window, the file list items have either:
- wrong height for a list item,
- wrong alignment of filename within an item box.

As it can be seen, the icon and filename are aligned to the bottom of the list item, while "Modified" sits in the center. Here's an illustration of what I mean by that:

![image](https://github.com/mallowigi/material-theme-issues/assets/77862767/fec40067-b5e4-4a06-a9b7-1465002b588a)

### To Reproduce

1. Produce a merge conflict.
2. Go to commit window and click on "Resolve".
3. See the window and improper alignment of text.

### Expected behavior

Filename and icon is aligned to the center of the box.

### Material Theme Version

8.13.2

### IDE

WebStorm

### System Info

```shell
WebStorm 2023.3.5
Build #WS-233.14808.24, built on March 13, 2024
Licensed to Jakub Kazimierczak
Subscription is active until November 4, 2024.
For educational use only.
Runtime version: 17.0.10+1-b1087.21 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 10.0
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 4
Registry:
  ide.balloon.shadow.size=0
  editor.focus.mode.color.light=6b727d
  editor.focus.mode.color.dark=6b727d
  ide.new.editor.tabs.vertical.borders=true
  ide.animate.toolwindows=true
  ide.editor.tab.selection.animation=true
Non-Bundled Plugins:
  com.github.lppedd.idea-conventional-commit (0.22.0)
  com.intellij.properties (233.11799.172)
  com.github.lppedd.idea-conventional-commit-commitlint (0.1.2)
  String Manipulation (9.12.0)
  hunspell (233.14808.24)
  net.seesharpsoft.intellij.plugins.file-preview (1.6.4)
  ru.adelf.idea.dotenv (2024.1)
  com.github.copilot (1.5.0.5148)
  com.mallowigi (94.1.0)
  mobi.hsz.idea.gitignore (4.5.2)
  com.intellij.database (233.14475.2)
  com.chrisrm.idea.MaterialThemeUI (8.13.2)
  jones.restarteslintaction.restart-eslint-action (0.0.1)
  mdx.js (233.11799.172)
```

### Logs/Screenshots

```shell
![image](https://github.com/mallowigi/material-theme-issues/assets/77862767/fec40067-b5e4-4a06-a9b7-1465002b588a)
```

**Comment by mallowigi** [comment]
This bug is not fixable, it has existed since the origin of the plugin and is due to the Project View's _Custom Item Line Height_. The more height you give, the more it will be "cropped"

Ex at max size
![CleanShot 2024-03-17 at 15 26 30@2x](https://github.com/mallowigi/material-theme-issues/assets/5015756/103d8f1d-bd1b-446f-9f12-7cccf4c3c88d)

Ex at min size
![CleanShot 2024-03-17 at 15 26 54@2x](https://github.com/mallowigi/material-theme-issues/assets/5015756/e9e396a8-0982-4c34-a91c-1f4707d118fd)

Since we're using JetBrains UI under the hood, there's no way to control this without forcing anyone to use "18".
